<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<title>Cadastro Habitacional</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="CadHabit Guarapuava">
	<meta name="author" content="Dayane Lustosa">

	<link rel="shortcut icon" type="image/x-icon" href="<?= BASE_URL ?>assets/cadhabitacional/img/brasao.gif" />
	<link href="<?= BASE_URL ?>assets/lightbox/css/lightbox.css" rel="stylesheet" />
	<link href="<?= BASE_URL ?>assets/bootstrap/css/bootstrap.css" rel="stylesheet">
	<link href="<?= BASE_URL ?>assets/cadhabitacional/css/style.css" rel="stylesheet">
	<link href="<?= BASE_URL ?>assets/chosen_v1.0.0/chosen.css" rel="stylesheet">
	<link rel="stylesheet" href="<?= BASE_URL?>assets/jquery-ui-1.10.4.custom/css/ui-lightness/jquery-ui-1.10.4.custom.min.css">
</head>
<body style="background-color: #EEE9E9;" onbeforeunload="confClose(event,0);" oncontextmenu='return false'>
	<hr />
	<hr />
	<div class="container">
		<nav class="navbar-inverse navbar-fixed-top navbar-default" style="z-index: 50000">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand cor" href="cadastro">
					<img src="<?= BASE_URL ?>assets/cadhabitacional/img/brasao.gif" width="20px">Habitacional
				</a>
			</div>
			<div class="collapse navbar-collapse" id="navbar-collapse">
				<ul class="nav navbar-nav active">
					<?php
					if (isset ( $_SESSION ['user'] ) && ($_SESSION['user']['atribuicao'] != 5)) { ?>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle"	data-toggle="dropdown">Cadastro
							<b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<?php
							if (isset ( $_SESSION ['user'] ) && (($_SESSION ['user'] ['atribuicao'] != 3) && ($_SESSION ['user'] ['atribuicao'] != 4))) { ?>
							<li>
								<a href="cadastro">Novo Requerente</a>
							</li>
							<?php
						} else if (isset ( $_SESSION ['user'] ) && (($_SESSION ['user'] ['atribuicao'] == 3) || ($_SESSION ['user'] ['atribuicao'] == 4))) { ?>
						<li>
							<a href="cadastro">Nova Pesquisa</a>
						</li>
						<?php
					}?>

					<?php
					if (isset ( $_SESSION ['user'] ) && (($_SESSION ['user'] ['atribuicao'] != 3) && ($_SESSION ['user'] ['atribuicao'] != 4))) { ?>
					<li>
						<a href="cadastrousuario"> Cadastrar Usuário </a>
					</li>
					<?php
				} else {
					echo '';
				}?>
				<?php
				if (isset ( $_SESSION ['user'] ) && (($_SESSION ['user'] ['atribuicao'] != 3) && ($_SESSION ['user'] ['atribuicao'] != 4))) { ?>
				<li>
					<a href="editausuario"> Editar Usuários </a>
				</li>
				<?php
			} else {
				echo '';
			}?>
		</ul>
	</li>
	<?php }?>

	<?php if (isset ( $_SESSION ['user'] ) && ($_SESSION['user']['atribuicao'] != 5)) { ?>
	<li class="dropdown">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown">Relatórios
			<b class="caret"></b>
		</a>
		<ul class="dropdown-menu">
			<?php
			if (isset ( $_SESSION ['user'] ) && (($_SESSION ['user'] ['atribuicao'] != 3) && ($_SESSION ['user'] ['atribuicao'] != 4))) {
				?>
				<li>
					<a href="relatorio">Relatório de Inscritos</a>
				</li>
				<li>
					<a href="relatorio/contemplados">Relatório de Contemplados</a>
				</li>
				<?php }
			} ?>
		</ul>
	</li>
</ul>
<ul class="nav navbar-nav active">
	<li>
		<a href="contato">Contato</a>
	</li>
</ul>

<?php
if(isset($_SESSION['user'])) { ?>
<ul class="nav navbar-nav navbar-right">
	<li class="dropdown">
		<a class="dropdown-toggle" data-toggle="dropdown" href="#">
			<?php if (isset ( $_SESSION ['user'] )) {
				echo '<span
				class="glyphicon glyphicon-cog"></span>' . " Olá, " . utf8_encode ( $_SESSION ['user'] ['name'] ) . '<b class="caret"></b>';
			} else {
				echo '';
			} ?>
		</a>
		<ul class="dropdown-menu" style="z-index: 20000">
			<li>
				<a tabindex="-1" href="editasenha">Alterar Senha</a>
			</li>
			<li class="divider"></li>
			<li>
				<a href="login">
					<?php if(isset($_SESSION['user'])) {
						echo 'Sair';
					} else { echo '';}?>
				</a>
			</li>
		</ul>
	</li>
</ul>
<?php
} else { ?>
<ul class="nav navbar-nav navbar-right">
	<li>
		<a href="login">
			<span class="glyphicon glyphicon-user"></span>
			<?php
			if(isset($_SESSION['user'])) {
				echo 'Sair';
			} else {
				?>
				Login
				<?php
			} ?>
		</a>
	</li>
</ul>
<?php } ?>
</div>
</nav>
<?php
$messages = new Library_FlashMessages();
$messages->getMessage();
?>

<?php
echo $this->content;
?>
</div>
<hr />
<div class=" col-md-12 rodape-div" align="center">
	<p>
		© 2013 Secretaria Municipal de Habitação e Urbanismo - GUARAPUAVA - Todos os direitos reservados
	</p>
</div>

<script type="text/javascript" src="<?= BASE_URL ?>assets/cadhabitacional/js/jquery.min.js"></script>
<script type="text/javascript" src="<?= BASE_URL ?>assets/bootstrap/js/bootstrap.js"></script>
<script src="<?= BASE_URL ?>assets/lightbox/js/lightbox-2.6.min.js"></script>
<script src="<?= BASE_URL ?>assets/chosen_v1.0.0/chosen.jquery.js"	type="text/javascript"></script>
<script src="<?= BASE_URL ?>assets/jQueryMask/jquery.mask.js" type="text/javascript"></script>
<script src="<?= BASE_URL ?>assets/jQueryMask/jquery.mask.min.js" type="text/javascript"></script>
<script src="<?= BASE_URL ?>assets/scriptcam/swfobject.js"></script>
<script src="<?= BASE_URL ?>assets/scriptcam/scriptcam.js"></script>
<script src="<?= BASE_URL ?>assets/cadhabitacional/js/webcam.js"></script>
<script type="text/javascript" src="<?= BASE_URL ?>assets/cadhabitacional/js/global.js"></script>
<script	src="<?= BASE_URL ?>assets/autocomplete/js/jquery-ui-1.10.4.custom.min.js"></script>
<script src="<?= BASE_URL ?>assets/cadhabitacional/js/dependents.js"></script>
</body>
</html>