<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="utf-8" />  
  <title>ERRO :: Cad Habitacional</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="shortcut icon" type="image/x-icon" href="<?= BASE_URL ?>assets/cadhabitacional/img/brasao.gif" />
  <link href="<?= BASE_URL ?>assets/lightbox/css/lightbox.css" rel="stylesheet" />
  <link href="<?= BASE_URL ?>assets/bootstrap/css/bootstrap.css" rel="stylesheet">
  <link href="<?= BASE_URL ?>assets/cadhabitacional/css/style.css" rel="stylesheet">
  <link href="<?= BASE_URL ?>assets/chosen_v1.0.0/chosen.css" rel="stylesheet">
  <link rel="stylesheet" href="<?= BASE_URL?>assets/jquery-ui-1.10.4.custom/css/ui-lightness/jquery-ui-1.10.4.custom.min.css">
</head>
<body style="background-color: #EEE9E9;" oncontextmenu='return false'>
  <hr />
  <hr />

  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <a class="navbar-brand" href="./">ERRO :: Cad Habitacional</a>
  </nav>

  <div class="container">
    <div class="col-md-12">
      <!-- Content -->
      <?= $this->content ?>
    </div>
  </div>
    <div class=" col-md-12 rodape-div" align="center">
      <p>
        © 2013 Secretaria Municipal de Habitação e Urbanismo - GUARAPUAVA - Todos os direitos reservados
      </p>

    </div>
  </div>
<!-- Javascripts -->
<script src="js/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
</body>
</html>
<?php exit(); ?>