<?php
$pesquisa = Database::findAll ( "SELECT hId, holderName, holderCpf, dtCadastro, atendido FROM pesquisa where atendido = 1 order by dtCadastro, holderName, holderCpf desc" );
$count = Database::findAll ( "Select hId FROM pesquisa where atendido = 1" );
$count = count ( $count );
?>
<style media="print">
.botao {
	display: none;
}
</style>

<div align="right"
	style="position: fixed; top: 150px; right: 4px; z-index: 1000;">
	<button id="btnPrintCont" type="button" class="btn btn-default botao"
		onclick="javascript:window.print();">
		<span class="glyphicon glyphicon-print"></span> Imprimir
	</button>
</div>

<?php
$formatfields = new FormatFields ();
$tbPesq = null;
foreach ( $pesquisa as $pesq ) :
	$tbPesq .= '<tr id="tbody-relatorio">
					<td> ' . strtoupper ( $pesq ['hId'] ) . ' </td>
					<td>' . $pesq ['holderName'] . '</td>
					<td>' . $formatfields->formatar ( $pesq ['holderCpf'], 'cpf') . '</td>
					<td>' . $pesq ['dtCadastro'] . '</td>
				<tr>';
endforeach
;
$tbPesquisa = '
<div class="container">
	<h2 align="center"><img src="../img/family.png" style="width: 60px"> Relatório de Contemplados </h2>
	<h3 align="center"> Foram encontrados ' . $count . ' registros de Contemplados</h3>
<table class="table table-hover">
	<thead>
		<tr>
			<th>Nº Inscrição</th>
			<th>Nome</th>
			<th>CPF</th>
			<th>Data Cadastro</th>
		</tr>
	</thead>
	<tbody id="tbody-relatorio">
		' . $tbPesq . '	
	</tbody>
</table>
</div>'?>
<?php echo $tbPesquisa; ?>